language: node_js
node_js:
  - "node"
cache: npm

before_script:
  - cd functions
  - npm ci
  - npm install firebase-tools -g
  - npm run build
script: firebase deploy --only functions --token $FIREBASE_TOKEN

branches:
  only:
    - travis
