language: node_js
node_js:
  - "node"
cache: npm

jobs:
  include:
    - stage: install
      script: cd functions
        - npm ci
        - npm install firebase-tools -g
    - stage: build
      script: npm run build
      if: branch != master
    - stage: deploy
      script: firebase deploy --only functions --token $FIREBASE_TOKEN
      if: branch = master
